version: '3.1'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: desafio5
      MYSQL_DATABASE: desafio5
      MYSQL_USER: desafio5
      MYSQL_PASSWORD: desafio5
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
